"""PlaceholderCallSession tests (app/voice/run.py) — the wiring glue between
SignalingServer and PeerSession that the compose entrypoint constructs per
call.

SKIP GUARD: skips only when the [voice] extra (aiortc/av) is absent, same
convention as tests/voice/test_peer_session.py.
"""

from __future__ import annotations

import pytest

pytest.importorskip("aiortc", reason="[voice] extra not installed")

import asyncio  # noqa: E402
import time  # noqa: E402
from datetime import UTC, datetime  # noqa: E402
from unittest.mock import AsyncMock, MagicMock  # noqa: E402

from aiortc import RTCConfiguration, RTCPeerConnection  # noqa: E402

import app.voice.run as run_module  # noqa: E402
from app.data.redis_client import SESSION_CONTROL_END, RedisClient  # noqa: E402
from app.domain.types import EndReason, Session, SessionState  # noqa: E402
from app.domain.voice import SignalMessage  # noqa: E402
from app.voice.run import (  # noqa: E402
    KNOWLEDGE_PREFETCH_TIMEOUT_S,
    PlaceholderCallSession,
    _BrainStack,
    _build_brain_stack,
    _make_brain_factory,
    _run_session_control_subscriber,
)
from tests.conftest import SettingsFactory  # noqa: E402
from tests.support.fake_redis import FakeRedis  # noqa: E402

_SESSION = Session(
    session_id="sess_1",
    user_id="usr_rajesh01",
    state=SessionState.IN_CALL,
    started_at=datetime(2026, 7, 24, 14, 14, tzinfo=UTC),
)


async def _real_offer_sdp() -> str:
    """A genuinely valid offer SDP (one audio track), generated by a
    throwaway peer — PeerSession.handle_offer() rejects anything else."""
    pc = RTCPeerConnection(RTCConfiguration(iceServers=[]))
    pc.addTransceiver("audio", direction="sendonly")
    offer = await pc.createOffer()
    await pc.setLocalDescription(offer)
    sdp = pc.localDescription.sdp
    await pc.close()
    return sdp


async def _noop_signal(message: SignalMessage) -> None:
    return None


async def test_egress_task_does_not_start_before_handle_offer() -> None:
    """Review HIGH finding: starting AudioEgress.run() at construction time
    runs its self-driven 20 ms cadence for however long the client takes to
    even send an offer, filling _EgressTrack's queue before anything drains
    it. The task must not exist until handle_offer() actually runs."""
    session = PlaceholderCallSession("sess-lazy-egress", _noop_signal, ice_servers=())
    try:
        assert session._egress_task is None
        await asyncio.sleep(0.1)  # would overflow the 50-frame cap if started
        assert session._egress_task is None
    finally:
        await session.close()


async def test_egress_task_starts_exactly_once_across_reoffers() -> None:
    session = PlaceholderCallSession("sess-egress-once", _noop_signal, ice_servers=())
    try:
        await session.handle_offer(await _real_offer_sdp())
        first_task = session._egress_task
        assert first_task is not None and not first_task.done()

        await session.handle_offer(await _real_offer_sdp())  # ICE-restart re-offer
        assert session._egress_task is first_task
    finally:
        await session.close()


async def test_close_before_any_offer_does_not_hang_or_raise() -> None:
    """The connection can close before the client ever sends an offer —
    _egress_task is still None then, and close() must handle that."""
    session = PlaceholderCallSession("sess-close-early", _noop_signal, ice_servers=())
    await asyncio.wait_for(session.close(), timeout=2)


# --------------------------------------------------------------------------
# Brain factory: the call-setup retrieval prefetch (Phase-5 memory wiring).
#
# These exist because an unwired collaborator is the failure mode this
# repo has already shipped once — a capture pipeline that was silently
# dead in production for a whole phase. A prefetch nobody calls looks
# exactly like a prefetch that found nothing.
# --------------------------------------------------------------------------


def _make_stack(context_builder: object) -> _BrainStack:
    session_manager = AsyncMock()
    session_manager.attach.return_value = _SESSION
    return _BrainStack(
        session_manager=session_manager,
        session_memory=MagicMock(),
        context_builder=context_builder,  # type: ignore[arg-type]
        prompt_builder=MagicMock(),
        tool_executor=MagicMock(),
        safety_layer=MagicMock(),
        llm_router=MagicMock(),
    )


async def test_brain_factory_prefetches_knowledge_once_for_the_attached_session() -> None:
    context_builder = AsyncMock()
    factory = _make_brain_factory(
        MagicMock(), MagicMock(), MagicMock(), _make_stack(context_builder)
    )

    await factory("sess_1")

    # The whole Session object, not just its id: a prefetch handed a
    # different session — or a synthesized one — would scope retrieval to
    # the wrong merchant, and that is the failure this asserts against.
    context_builder.prefetch_knowledge.assert_awaited_once_with(_SESSION)


def test_brain_stack_wires_an_embeddings_provider_when_a_key_is_configured(
    settings_factory: SettingsFactory,
) -> None:
    """The other half of the wiring nobody was exercising: `_build_brain_stack`
    is what decides whether retrieval is available at all."""
    stack = _build_brain_stack(
        settings_factory(), MagicMock(), MagicMock(), MagicMock()
    )

    assert stack.context_builder._embeddings is not None  # noqa: SLF001


def test_brain_stack_boots_with_no_openai_key_and_disables_retrieval(
    settings_factory: SettingsFactory,
) -> None:
    """Security review L7. `Settings.openai_api_key` is optional and
    `OpenAIEmbeddings` fail-fasts on a missing one, so constructing it
    unconditionally would take the whole worker down at startup rather
    than degrading the RAG slot — docs/09 §11's drop-rung 1 says the
    opposite. Asserted as `is None`, the state `prefetch_knowledge` checks,
    not merely "construction did not raise"."""
    stack = _build_brain_stack(
        settings_factory(openai_api_key=None), MagicMock(), MagicMock(), MagicMock()
    )

    assert stack.context_builder._embeddings is None  # noqa: SLF001


async def test_a_hanging_prefetch_cannot_block_call_setup_forever() -> None:
    """The bound exists because this runs on the path a merchant is
    waiting on. Asserted against wall-clock time, so removing the
    `wait_for` fails it rather than merely changing a log line."""

    class HangingContextBuilder:
        async def prefetch_knowledge(self, session: object) -> None:
            await asyncio.sleep(60)

    factory = _make_brain_factory(
        MagicMock(), MagicMock(), MagicMock(), _make_stack(HangingContextBuilder())
    )

    started = time.perf_counter()
    brain = await asyncio.wait_for(factory("sess_1"), timeout=KNOWLEDGE_PREFETCH_TIMEOUT_S + 5)
    elapsed = time.perf_counter() - started

    assert brain is not None  # the call proceeds without a knowledge slot
    assert elapsed < KNOWLEDGE_PREFETCH_TIMEOUT_S + 2


# --------------------------------------------------------------------------
# Post-call-pipeline-wiring: `_make_brain_factory`'s `on_call_ended`
# closure must finalize THIS call's CostTracker before ending the session,
# with the literal session_id/reason it was invoked with — the ordering
# `SessionManager.end()` itself enforces by raising `RuntimeError` when
# violated (session_manager.py judgment call 9).
# --------------------------------------------------------------------------


async def test_on_call_ended_finalizes_then_ends_with_the_literal_session_id_and_reason(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Patches `CostTracker` itself (rather than trying to drive the real
    one through mocked Postgres/Redis) so this test is purely about what
    `run.py`'s own wiring code does: call `finalize(session_id)` BEFORE
    `end(session_id, reason)`, on the SAME `CostTracker` instance
    `ConversationManager` is holding, with values that are literal here —
    never derived by calling back into the factory's own recorded args."""
    calls: list[tuple[str, ...]] = []

    class _RecordingCostTracker:
        def __init__(self, *args: object, **kwargs: object) -> None:
            pass

        async def finalize(self, session_id: str) -> None:
            calls.append(("finalize", session_id))

    monkeypatch.setattr(run_module, "CostTracker", _RecordingCostTracker)

    async def _end(session_id: str, reason: EndReason) -> None:
        calls.append(("end", session_id, reason.value))

    stack = _make_stack(AsyncMock())
    stack.session_manager.end.side_effect = _end
    factory = _make_brain_factory(MagicMock(), MagicMock(), MagicMock(), stack)

    built = await factory("sess_1")
    await built.on_call_ended(EndReason.HANGUP)

    assert calls == [("finalize", "sess_1"), ("end", "sess_1", "hangup")]


async def test_on_call_ended_forwards_the_error_reason_unchanged(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A second, independent case for the reason argument specifically —
    proves `on_call_ended` doesn't hardcode HANGUP or otherwise drop the
    reason the worker computed."""
    calls: list[tuple[str, ...]] = []

    class _RecordingCostTracker:
        def __init__(self, *args: object, **kwargs: object) -> None:
            pass

        async def finalize(self, session_id: str) -> None:
            calls.append(("finalize", session_id))

    monkeypatch.setattr(run_module, "CostTracker", _RecordingCostTracker)

    async def _end(session_id: str, reason: EndReason) -> None:
        calls.append(("end", session_id, reason.value))

    stack = _make_stack(AsyncMock())
    stack.session_manager.end.side_effect = _end
    factory = _make_brain_factory(MagicMock(), MagicMock(), MagicMock(), stack)

    built = await factory("sess_1")
    await built.on_call_ended(EndReason.ERROR)

    assert calls == [("finalize", "sess_1"), ("end", "sess_1", "error")]


# --------------------------------------------------------------------------
# The session_control:{id} subscriber — the missing half of docs/13 §2.2's
# operator DELETE (sessions.py's own judgment call 1: agent-api publishes
# "end" into a channel nothing was ever listening on).
# --------------------------------------------------------------------------


class _SpyServer:
    """`SignalingServer`-shaped double: records `close_one()` calls
    without needing a real signaling stack — the subscriber's OWN
    behavior (parse the channel, filter the message, call close_one) is
    what this proves; close_one()'s own correctness has its own tests in
    tests/voice/test_signaling_server.py."""

    def __init__(self, *, closed_return: bool = True) -> None:
        self.calls: list[tuple[str, str]] = []
        self._closed_return = closed_return

    async def close_one(self, session_id: str, *, reason: str) -> bool:
        self.calls.append((session_id, reason))
        return self._closed_return


async def test_session_control_subscriber_closes_the_session_on_end_message() -> None:
    fake_redis = FakeRedis()
    redis = RedisClient(fake_redis, session_ttl_seconds=60)  # type: ignore[arg-type]
    server = _SpyServer()

    task = asyncio.create_task(_run_session_control_subscriber(redis, server))  # type: ignore[arg-type]
    try:
        await asyncio.sleep(0)  # let the subscriber's psubscribe land first
        await redis.publish_session_control("sess_1", SESSION_CONTROL_END)
        for _ in range(50):
            if server.calls:
                break
            await asyncio.sleep(0.01)
    finally:
        task.cancel()
        await asyncio.gather(task, return_exceptions=True)

    # The literal (session_id, reason) pair — not re-derived from the
    # subscriber's own call — and nothing else on the channel.
    assert server.calls == [("sess_1", "operator_hangup")]


async def test_session_control_subscriber_ignores_non_end_messages() -> None:
    fake_redis = FakeRedis()
    redis = RedisClient(fake_redis, session_ttl_seconds=60)  # type: ignore[arg-type]
    server = _SpyServer()

    task = asyncio.create_task(_run_session_control_subscriber(redis, server))  # type: ignore[arg-type]
    try:
        await asyncio.sleep(0)
        await redis.publish_session_control("sess_1", "some-other-message")
        # A real message right after — if the subscriber were wedged by
        # the ignored one, this would never arrive either.
        await redis.publish_session_control("sess_2", SESSION_CONTROL_END)
        for _ in range(50):
            if server.calls:
                break
            await asyncio.sleep(0.01)
    finally:
        task.cancel()
        await asyncio.gather(task, return_exceptions=True)

    assert server.calls == [("sess_2", "operator_hangup")]


async def test_session_control_subscriber_survives_a_handler_exception() -> None:
    """House rule: one bad message must not take the whole subscriber (and
    therefore every future operator hang-up on this worker) down with it."""
    fake_redis = FakeRedis()
    redis = RedisClient(fake_redis, session_ttl_seconds=60)  # type: ignore[arg-type]

    class _ExplodingThenSpyServer(_SpyServer):
        async def close_one(self, session_id: str, *, reason: str) -> bool:
            if session_id == "sess-boom":
                raise RuntimeError("boom")
            return await super().close_one(session_id, reason=reason)

    server = _ExplodingThenSpyServer()
    task = asyncio.create_task(_run_session_control_subscriber(redis, server))  # type: ignore[arg-type]
    try:
        await asyncio.sleep(0)
        await redis.publish_session_control("sess-boom", SESSION_CONTROL_END)
        await redis.publish_session_control("sess_2", SESSION_CONTROL_END)
        for _ in range(50):
            if server.calls:
                break
            await asyncio.sleep(0.01)
    finally:
        task.cancel()
        await asyncio.gather(task, return_exceptions=True)

    assert server.calls == [("sess_2", "operator_hangup")]
