"""PlaceholderCallSession tests (app/voice/run.py) — the wiring glue between
SignalingServer and PeerSession that the compose entrypoint constructs per
call.

SKIP GUARD: skips only when the [voice] extra (aiortc/av) is absent, same
convention as tests/voice/test_peer_session.py.
"""

from __future__ import annotations

import pytest

pytest.importorskip("aiortc", reason="[voice] extra not installed")

import asyncio  # noqa: E402
import time  # noqa: E402
from datetime import UTC, datetime  # noqa: E402
from decimal import Decimal  # noqa: E402
from unittest.mock import AsyncMock, MagicMock  # noqa: E402

from aiortc import RTCConfiguration, RTCPeerConnection  # noqa: E402

import app.voice.run as run_module  # noqa: E402
from app.data.redis_client import SESSION_CONTROL_END, RedisClient  # noqa: E402
from app.domain.types import (  # noqa: E402
    EndReason,
    Message,
    ModelTier,
    Role,
    Session,
    SessionState,
    TaskKind,
    TokenEvent,
    TurnCost,
    UsageEvent,
)
from app.domain.voice import SignalMessage  # noqa: E402
from app.voice.run import (  # noqa: E402
    KNOWLEDGE_PREFETCH_TIMEOUT_S,
    PlaceholderCallSession,
    _BrainStack,
    _build_brain_stack,
    _make_brain_factory,
    _run_session_control_subscriber,
)
from tests.conftest import SettingsFactory  # noqa: E402
from tests.support.fake_redis import FakeRedis  # noqa: E402

_SESSION = Session(
    session_id="sess_1",
    user_id="usr_rajesh01",
    state=SessionState.IN_CALL,
    started_at=datetime(2026, 7, 24, 14, 14, tzinfo=UTC),
)


async def _real_offer_sdp() -> str:
    """A genuinely valid offer SDP (one audio track), generated by a
    throwaway peer — PeerSession.handle_offer() rejects anything else."""
    pc = RTCPeerConnection(RTCConfiguration(iceServers=[]))
    pc.addTransceiver("audio", direction="sendonly")
    offer = await pc.createOffer()
    await pc.setLocalDescription(offer)
    sdp = pc.localDescription.sdp
    await pc.close()
    return sdp


async def _noop_signal(message: SignalMessage) -> None:
    return None


async def test_egress_task_does_not_start_before_handle_offer() -> None:
    """Review HIGH finding: starting AudioEgress.run() at construction time
    runs its self-driven 20 ms cadence for however long the client takes to
    even send an offer, filling _EgressTrack's queue before anything drains
    it. The task must not exist until handle_offer() actually runs."""
    session = PlaceholderCallSession("sess-lazy-egress", _noop_signal, ice_servers=())
    try:
        assert session._egress_task is None
        await asyncio.sleep(0.1)  # would overflow the 50-frame cap if started
        assert session._egress_task is None
    finally:
        await session.close()


async def test_egress_task_starts_exactly_once_across_reoffers() -> None:
    session = PlaceholderCallSession("sess-egress-once", _noop_signal, ice_servers=())
    try:
        await session.handle_offer(await _real_offer_sdp())
        first_task = session._egress_task
        assert first_task is not None and not first_task.done()

        await session.handle_offer(await _real_offer_sdp())  # ICE-restart re-offer
        assert session._egress_task is first_task
    finally:
        await session.close()


async def test_close_before_any_offer_does_not_hang_or_raise() -> None:
    """The connection can close before the client ever sends an offer —
    _egress_task is still None then, and close() must handle that."""
    session = PlaceholderCallSession("sess-close-early", _noop_signal, ice_servers=())
    await asyncio.wait_for(session.close(), timeout=2)


# --------------------------------------------------------------------------
# Brain factory: the call-setup retrieval prefetch (Phase-5 memory wiring).
#
# These exist because an unwired collaborator is the failure mode this
# repo has already shipped once — a capture pipeline that was silently
# dead in production for a whole phase. A prefetch nobody calls looks
# exactly like a prefetch that found nothing.
# --------------------------------------------------------------------------


def _make_stack(context_builder: object) -> _BrainStack:
    session_manager = AsyncMock()
    session_manager.attach.return_value = _SESSION
    return _BrainStack(
        session_manager=session_manager,
        session_memory=MagicMock(),
        context_builder=context_builder,  # type: ignore[arg-type]
        prompt_builder=MagicMock(),
        tool_executor=MagicMock(),
        safety_layer=MagicMock(),
        llm_router=MagicMock(),
    )


async def test_brain_factory_prefetches_knowledge_once_for_the_attached_session() -> None:
    context_builder = AsyncMock()
    factory = _make_brain_factory(
        MagicMock(), MagicMock(), MagicMock(), _make_stack(context_builder)
    )

    await factory("sess_1")

    # The whole Session object, not just its id: a prefetch handed a
    # different session — or a synthesized one — would scope retrieval to
    # the wrong merchant, and that is the failure this asserts against.
    context_builder.prefetch_knowledge.assert_awaited_once_with(_SESSION)


def test_brain_stack_wires_an_embeddings_provider_when_a_key_is_configured(
    settings_factory: SettingsFactory,
) -> None:
    """The other half of the wiring nobody was exercising: `_build_brain_stack`
    is what decides whether retrieval is available at all."""
    stack = _build_brain_stack(
        settings_factory(), MagicMock(), MagicMock(), MagicMock()
    )

    assert stack.context_builder._embeddings is not None  # noqa: SLF001


def test_brain_stack_boots_with_no_openai_key_and_disables_retrieval(
    settings_factory: SettingsFactory,
) -> None:
    """Security review L7. `Settings.openai_api_key` is optional and
    `OpenAIEmbeddings` fail-fasts on a missing one, so constructing it
    unconditionally would take the whole worker down at startup rather
    than degrading the RAG slot — docs/09 §11's drop-rung 1 says the
    opposite. Asserted as `is None`, the state `prefetch_knowledge` checks,
    not merely "construction did not raise"."""
    stack = _build_brain_stack(
        settings_factory(openai_api_key=None), MagicMock(), MagicMock(), MagicMock()
    )

    assert stack.context_builder._embeddings is None  # noqa: SLF001


async def test_a_hanging_prefetch_cannot_block_call_setup_forever() -> None:
    """The bound exists because this runs on the path a merchant is
    waiting on. Asserted against wall-clock time, so removing the
    `wait_for` fails it rather than merely changing a log line."""

    class HangingContextBuilder:
        async def prefetch_knowledge(self, session: object) -> None:
            await asyncio.sleep(60)

    factory = _make_brain_factory(
        MagicMock(), MagicMock(), MagicMock(), _make_stack(HangingContextBuilder())
    )

    started = time.perf_counter()
    brain = await asyncio.wait_for(factory("sess_1"), timeout=KNOWLEDGE_PREFETCH_TIMEOUT_S + 5)
    elapsed = time.perf_counter() - started

    assert brain is not None  # the call proceeds without a knowledge slot
    assert elapsed < KNOWLEDGE_PREFETCH_TIMEOUT_S + 2


# --------------------------------------------------------------------------
# Post-call-pipeline-wiring: `_make_brain_factory`'s `on_call_ended`
# closure must finalize THIS call's CostTracker before ending the session,
# with the literal session_id/reason it was invoked with — the ordering
# `SessionManager.end()` itself enforces by raising `RuntimeError` when
# violated (session_manager.py judgment call 9).
# --------------------------------------------------------------------------


async def test_on_call_ended_finalizes_then_ends_with_the_literal_session_id_and_reason(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Patches `CostTracker` itself (rather than trying to drive the real
    one through mocked Postgres/Redis) so this test is purely about what
    `run.py`'s own wiring code does: call `finalize(session_id)` BEFORE
    `end(session_id, reason)`, on the SAME `CostTracker` instance
    `ConversationManager` is holding, with values that are literal here —
    never derived by calling back into the factory's own recorded args."""
    calls: list[tuple[str, ...]] = []

    class _RecordingCostTracker:
        def __init__(self, *args: object, **kwargs: object) -> None:
            pass

        async def finalize(self, session_id: str) -> None:
            calls.append(("finalize", session_id))

    monkeypatch.setattr(run_module, "CostTracker", _RecordingCostTracker)

    async def _end(
        session_id: str, reason: EndReason, *, real_summarizer: object = None
    ) -> None:
        calls.append(("end", session_id, reason.value))

    stack = _make_stack(AsyncMock())
    stack.session_manager.end.side_effect = _end
    factory = _make_brain_factory(MagicMock(), MagicMock(), MagicMock(), stack)

    built = await factory("sess_1")
    await built.on_call_ended(EndReason.HANGUP)

    assert calls == [("finalize", "sess_1"), ("end", "sess_1", "hangup")]


async def test_on_call_ended_forwards_the_error_reason_unchanged(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A second, independent case for the reason argument specifically —
    proves `on_call_ended` doesn't hardcode HANGUP or otherwise drop the
    reason the worker computed."""
    calls: list[tuple[str, ...]] = []

    class _RecordingCostTracker:
        def __init__(self, *args: object, **kwargs: object) -> None:
            pass

        async def finalize(self, session_id: str) -> None:
            calls.append(("finalize", session_id))

    monkeypatch.setattr(run_module, "CostTracker", _RecordingCostTracker)

    async def _end(
        session_id: str, reason: EndReason, *, real_summarizer: object = None
    ) -> None:
        calls.append(("end", session_id, reason.value))

    stack = _make_stack(AsyncMock())
    stack.session_manager.end.side_effect = _end
    factory = _make_brain_factory(MagicMock(), MagicMock(), MagicMock(), stack)

    built = await factory("sess_1")
    await built.on_call_ended(EndReason.ERROR)

    assert calls == [("finalize", "sess_1"), ("end", "sess_1", "error")]


# --------------------------------------------------------------------------
# HIGH fix (post-call-pipeline-wiring review): SessionManager.end() failing
# AFTER CostTracker.finalize() already committed must not permanently wedge
# the session — a bounded retry recovers from a transient blip, and an
# unrecovered failure must be loud and distinguishable from routine
# worker-crash noise.
# --------------------------------------------------------------------------


async def test_on_call_ended_retries_a_transient_end_failure_and_recovers(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """end() failing once (a transient blip) then succeeding must not
    surface as an error at all — the call completes normally, with
    end() actually having been called the literal number of times this
    test scripts, not a value re-derived from the retry loop's own
    counter."""
    calls: list[tuple[str, ...]] = []

    class _RecordingCostTracker:
        def __init__(self, *args: object, **kwargs: object) -> None:
            pass

        async def finalize(self, session_id: str) -> None:
            calls.append(("finalize", session_id))

    monkeypatch.setattr(run_module, "CostTracker", _RecordingCostTracker)
    # No real sleeping in a unit test — the backoff itself isn't what this
    # test is about, and a 0.5s+1.0s wait would make the suite slower for
    # no assertion value.
    monkeypatch.setattr(run_module.asyncio, "sleep", AsyncMock())

    attempts = {"n": 0}

    async def _end(
        session_id: str, reason: EndReason, *, real_summarizer: object = None
    ) -> None:
        attempts["n"] += 1
        if attempts["n"] == 1:
            raise RuntimeError("transient db blip")
        calls.append(("end", session_id, reason.value))

    stack = _make_stack(AsyncMock())
    stack.session_manager.end.side_effect = _end
    factory = _make_brain_factory(MagicMock(), MagicMock(), MagicMock(), stack)

    built = await factory("sess_1")
    await built.on_call_ended(EndReason.HANGUP)  # must not raise

    assert calls == [("finalize", "sess_1"), ("end", "sess_1", "hangup")]
    assert attempts["n"] == 2


async def test_on_call_ended_raises_after_exhausting_end_retries(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A persistent end() failure must still propagate (so the existing
    task-failure visibility, CallSession._log_worker_crash, sees it) —
    after trying the literal number of times `_END_RETRY_ATTEMPTS`
    configures, not an arbitrary or unbounded number."""
    class _RecordingCostTracker:
        def __init__(self, *args: object, **kwargs: object) -> None:
            pass

        async def finalize(self, session_id: str) -> None:
            pass

    monkeypatch.setattr(run_module, "CostTracker", _RecordingCostTracker)
    monkeypatch.setattr(run_module.asyncio, "sleep", AsyncMock())

    async def _always_fails(
        session_id: str, reason: EndReason, *, real_summarizer: object = None
    ) -> None:
        raise RuntimeError("db is down")

    stack = _make_stack(AsyncMock())
    stack.session_manager.end.side_effect = _always_fails
    factory = _make_brain_factory(MagicMock(), MagicMock(), MagicMock(), stack)

    built = await factory("sess_1")

    with pytest.raises(RuntimeError, match="db is down"):
        await built.on_call_ended(EndReason.HANGUP)

    assert stack.session_manager.end.await_count == 3


async def test_on_call_ended_logs_a_distinct_alert_worthy_event_when_end_is_never_recovered(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The loud-and-distinguishable requirement, checked directly against
    the actual log call rather than inferred from behavior: the specific
    event name `voice_worker.session_end_failed_after_finalize` (not a
    generic crash message) must fire at ERROR level with the session_id
    this call was actually for."""
    class _RecordingCostTracker:
        def __init__(self, *args: object, **kwargs: object) -> None:
            pass

        async def finalize(self, session_id: str) -> None:
            pass

    monkeypatch.setattr(run_module, "CostTracker", _RecordingCostTracker)
    monkeypatch.setattr(run_module.asyncio, "sleep", AsyncMock())

    async def _always_fails(
        session_id: str, reason: EndReason, *, real_summarizer: object = None
    ) -> None:
        raise RuntimeError("db is down")

    stack = _make_stack(AsyncMock())
    stack.session_manager.end.side_effect = _always_fails
    factory = _make_brain_factory(MagicMock(), MagicMock(), MagicMock(), stack)
    built = await factory("sess_1")

    logged_error = MagicMock()
    monkeypatch.setattr(run_module.log, "error", logged_error)

    with pytest.raises(RuntimeError):
        await built.on_call_ended(EndReason.HANGUP)

    logged_error.assert_called_once_with(
        "voice_worker.session_end_failed_after_finalize",
        session_id="sess_1",
        reason="hangup",
        attempts=3,
        exc_info=True,
    )


# --------------------------------------------------------------------------
# summarizer-turn-loop-wiring task: `_make_brain_factory` now also builds a
# real per-call `Summarizer`, shares it with `ConversationManager`, and
# `on_call_ended` must drain it before `finalize()` — the orphaned-fold fix
# `Summarizer`'s own class docstring asks for.
# --------------------------------------------------------------------------


class _BlockingRouter:
    """`LLMRouterProto` double whose stream parks on an `asyncio.Event`
    the test owns — the same shape tests/memory/test_summarizer.py's own
    `_BlockingRouter` uses, reproduced locally here (not imported) so
    this file stays independent of that module's private test helpers.
    Exists so a test can observe the window in which a fold has been
    scheduled but has NOT produced anything yet — the only state that
    distinguishes "kicked off the turn path" from "awaited on it"."""

    def __init__(self, reply: str = "folded summary") -> None:
        self.gate = asyncio.Event()
        self.started = asyncio.Event()
        self._reply = reply

    def route(self, task: TaskKind) -> ModelTier:
        return ModelTier.UTILITY if task is TaskKind.UTILITY else ModelTier.DIALOGUE

    def stream(
        self,
        messages: list[Message],
        *,
        tier: ModelTier,
        tools: list[dict[str, object]] | None = None,
        ttft_deadline_s: float = 1.5,
    ) -> object:
        return self._events()

    async def _events(self) -> object:
        self.started.set()
        await self.gate.wait()
        yield TokenEvent(delta={"content": self._reply})
        yield UsageEvent(model="anthropic/claude-haiku-4-5", usage={"prompt_tokens": 100})


async def test_the_real_summarizer_and_conversation_manager_share_one_cost_tracker(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Point 5 of the summarizer-turn-loop-wiring task: a fold's cost
    must land in the SAME `CostTracker` instance `finalize()` reads, not
    a second one nothing reads. Proven by construction count — exactly
    one `CostTracker` must be built per call, and both collaborators must
    hold that SAME instance (identity, not just equal-looking mocks)."""
    constructed: list[object] = []

    class _RecordingCostTracker:
        def __init__(self, *args: object, **kwargs: object) -> None:
            constructed.append(self)

        async def finalize(self, session_id: str) -> None:
            pass

    monkeypatch.setattr(run_module, "CostTracker", _RecordingCostTracker)
    stack = _make_stack(AsyncMock())
    factory = _make_brain_factory(MagicMock(), MagicMock(), MagicMock(), stack)

    built = await factory("sess_1")

    assert len(constructed) == 1
    assert built.brain._cost_tracker is constructed[0]  # noqa: SLF001
    assert built.brain._summarizer._cost_tracker is constructed[0]  # noqa: SLF001


async def test_on_call_ended_drains_an_in_flight_fold_before_finalize(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The single most important test in this task: the orphaned-fold
    hazard, stated by `Summarizer`'s own class docstring — the default
    `task_factory` (`asyncio.create_task`) schedules a fold OUTSIDE any
    `TaskGroup`, so without something explicitly awaiting it, an
    in-flight fold keeps running after call teardown and its eventual
    `cost_tracker.record_turn()` call (inside `_consume`, when the usage
    frame arrives) lands AFTER `finalize()` already upserted `call_costs`
    — orphaned, landing nowhere.

    Proves the fix: `on_call_ended`'s `summarizer.drain()` call blocks
    until the in-flight fold finishes, and that happens BEFORE
    `finalize()` runs. This is proven two ways, either of which alone
    would fail on the pre-fix code (`await cost_tracker.finalize(...)`
    called with no `drain()` first): first, `on_call_ended` must still
    be RUNNING (not done) while the fold is parked on the gate — without
    `drain()`, `finalize()`/`end()` have no blocking call to wait on and
    the whole coroutine completes almost immediately, so `end_task.done()`
    would already be `True` at the `assert not end_task.done()` line, and
    `order` would already contain "finalize" before the gate is ever
    released. Second, once the gate opens, `record_turn` must appear in
    `order` strictly BEFORE `finalize` — the fold's cost actually landed
    in the tracker's running total before the total was read."""
    order: list[str] = []

    class _RecordingCostTracker:
        def __init__(self, *args: object, **kwargs: object) -> None:
            pass

        def record_turn(self, usage: object, model: str, span: object) -> TurnCost:
            order.append("record_turn")
            return TurnCost(
                model=model, input_tokens=0, output_tokens=0, cost_usd=Decimal("0.0023")
            )

        async def finalize(self, session_id: str) -> None:
            order.append("finalize")

    monkeypatch.setattr(run_module, "CostTracker", _RecordingCostTracker)

    # `_BrainStack` is frozen — built directly here (not via `_make_stack`)
    # so `llm_router`/`session_memory` can be the controllable doubles
    # this test needs, rather than mutated after construction.
    router = _BlockingRouter()
    session_manager = AsyncMock()
    session_manager.attach.return_value = _SESSION
    stack = _BrainStack(
        session_manager=session_manager,
        session_memory=AsyncMock(),
        context_builder=AsyncMock(),  # type: ignore[arg-type]
        prompt_builder=MagicMock(),
        tool_executor=MagicMock(),
        safety_layer=MagicMock(),
        llm_router=router,  # type: ignore[arg-type]
    )
    factory = _make_brain_factory(MagicMock(), MagicMock(), MagicMock(), stack)

    built = await factory("sess_1")
    summarizer = built.brain._summarizer  # noqa: SLF001

    # Populate the buffer and kick a fold exactly the way the turn loop
    # does (ConversationManager's own judgment call #13), then hold it
    # mid-stream — simulating hang-up landing while a fold is in flight.
    for turn_no in range(1, 10):
        summarizer.observe_turn(turn_no, [Message(role=Role.USER, content=f"line {turn_no}")])
    assert summarizer.kick("sess_1", 9) is True
    await asyncio.wait_for(router.started.wait(), timeout=2.0)

    end_task = asyncio.create_task(built.on_call_ended(EndReason.HANGUP))
    await asyncio.sleep(0)  # let on_call_ended run up to `await summarizer.drain()`
    assert not end_task.done(), (
        "on_call_ended finished without waiting for the in-flight fold — "
        "the drain() fix is missing or was skipped"
    )
    assert order == []  # finalize() has not run yet either

    router.gate.set()  # release the fold's model call
    await asyncio.wait_for(end_task, timeout=5.0)

    assert order == ["record_turn", "finalize"]
    assert summarizer.summary is not None  # the fold actually completed, not orphaned


async def test_on_call_ended_passes_the_real_summarizer_to_session_manager_end(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The tail-turn-gap closure (session_manager.py judgment call #12):
    `end()` must receive the SAME real per-call `Summarizer`
    `ConversationManager` was buffering turns into — not a fresh one — so
    its final `fold_pending()` call reaches real content."""

    class _RecordingCostTracker:
        def __init__(self, *args: object, **kwargs: object) -> None:
            pass

        async def finalize(self, session_id: str) -> None:
            pass

    monkeypatch.setattr(run_module, "CostTracker", _RecordingCostTracker)

    stack = _make_stack(AsyncMock())
    factory = _make_brain_factory(MagicMock(), MagicMock(), MagicMock(), stack)

    built = await factory("sess_1")
    await built.on_call_ended(EndReason.HANGUP)

    stack.session_manager.end.assert_awaited_once()
    _, kwargs = stack.session_manager.end.await_args
    assert kwargs["real_summarizer"] is built.brain._summarizer  # noqa: SLF001


# --------------------------------------------------------------------------
# The session_control:{id} subscriber — the missing half of docs/13 §2.2's
# operator DELETE (sessions.py's own judgment call 1: agent-api publishes
# "end" into a channel nothing was ever listening on).
# --------------------------------------------------------------------------


class _SpyServer:
    """`SignalingServer`-shaped double: records `close_one()` calls
    without needing a real signaling stack — the subscriber's OWN
    behavior (parse the channel, filter the message, call close_one) is
    what this proves; close_one()'s own correctness has its own tests in
    tests/voice/test_signaling_server.py."""

    def __init__(self, *, closed_return: bool = True) -> None:
        self.calls: list[tuple[str, str]] = []
        self._closed_return = closed_return

    async def close_one(self, session_id: str, *, reason: str) -> bool:
        self.calls.append((session_id, reason))
        return self._closed_return


async def test_session_control_subscriber_closes_the_session_on_end_message() -> None:
    fake_redis = FakeRedis()
    redis = RedisClient(fake_redis, session_ttl_seconds=60)  # type: ignore[arg-type]
    server = _SpyServer()

    task = asyncio.create_task(_run_session_control_subscriber(redis, server))  # type: ignore[arg-type]
    try:
        await asyncio.sleep(0)  # let the subscriber's psubscribe land first
        await redis.publish_session_control("sess_1", SESSION_CONTROL_END)
        for _ in range(50):
            if server.calls:
                break
            await asyncio.sleep(0.01)
    finally:
        task.cancel()
        await asyncio.gather(task, return_exceptions=True)

    # The literal (session_id, reason) pair — not re-derived from the
    # subscriber's own call — and nothing else on the channel.
    assert server.calls == [("sess_1", "operator_hangup")]


async def test_session_control_subscriber_ignores_non_end_messages() -> None:
    fake_redis = FakeRedis()
    redis = RedisClient(fake_redis, session_ttl_seconds=60)  # type: ignore[arg-type]
    server = _SpyServer()

    task = asyncio.create_task(_run_session_control_subscriber(redis, server))  # type: ignore[arg-type]
    try:
        await asyncio.sleep(0)
        await redis.publish_session_control("sess_1", "some-other-message")
        # A real message right after — if the subscriber were wedged by
        # the ignored one, this would never arrive either.
        await redis.publish_session_control("sess_2", SESSION_CONTROL_END)
        for _ in range(50):
            if server.calls:
                break
            await asyncio.sleep(0.01)
    finally:
        task.cancel()
        await asyncio.gather(task, return_exceptions=True)

    assert server.calls == [("sess_2", "operator_hangup")]


async def test_session_control_subscriber_survives_a_handler_exception() -> None:
    """House rule: one bad message must not take the whole subscriber (and
    therefore every future operator hang-up on this worker) down with it."""
    fake_redis = FakeRedis()
    redis = RedisClient(fake_redis, session_ttl_seconds=60)  # type: ignore[arg-type]

    class _ExplodingThenSpyServer(_SpyServer):
        async def close_one(self, session_id: str, *, reason: str) -> bool:
            if session_id == "sess-boom":
                raise RuntimeError("boom")
            return await super().close_one(session_id, reason=reason)

    server = _ExplodingThenSpyServer()
    task = asyncio.create_task(_run_session_control_subscriber(redis, server))  # type: ignore[arg-type]
    try:
        await asyncio.sleep(0)
        await redis.publish_session_control("sess-boom", SESSION_CONTROL_END)
        await redis.publish_session_control("sess_2", SESSION_CONTROL_END)
        for _ in range(50):
            if server.calls:
                break
            await asyncio.sleep(0.01)
    finally:
        task.cancel()
        await asyncio.gather(task, return_exceptions=True)

    assert server.calls == [("sess_2", "operator_hangup")]
