"""PlaceholderCallSession tests (app/voice/run.py) — the wiring glue between
SignalingServer and PeerSession that the compose entrypoint constructs per
call.

SKIP GUARD: skips only when the [voice] extra (aiortc/av) is absent, same
convention as tests/voice/test_peer_session.py.
"""

from __future__ import annotations

import pytest

pytest.importorskip("aiortc", reason="[voice] extra not installed")

import asyncio  # noqa: E402

from aiortc import RTCConfiguration, RTCPeerConnection  # noqa: E402

from app.domain.voice import SignalMessage  # noqa: E402
from app.voice.run import PlaceholderCallSession  # noqa: E402


async def _real_offer_sdp() -> str:
    """A genuinely valid offer SDP (one audio track), generated by a
    throwaway peer — PeerSession.handle_offer() rejects anything else."""
    pc = RTCPeerConnection(RTCConfiguration(iceServers=[]))
    pc.addTransceiver("audio", direction="sendonly")
    offer = await pc.createOffer()
    await pc.setLocalDescription(offer)
    sdp = pc.localDescription.sdp
    await pc.close()
    return sdp


async def _noop_signal(message: SignalMessage) -> None:
    return None


async def test_egress_task_does_not_start_before_handle_offer() -> None:
    """Review HIGH finding: starting AudioEgress.run() at construction time
    runs its self-driven 20 ms cadence for however long the client takes to
    even send an offer, filling _EgressTrack's queue before anything drains
    it. The task must not exist until handle_offer() actually runs."""
    session = PlaceholderCallSession("sess-lazy-egress", _noop_signal, ice_servers=())
    try:
        assert session._egress_task is None
        await asyncio.sleep(0.1)  # would overflow the 50-frame cap if started
        assert session._egress_task is None
    finally:
        await session.close()


async def test_egress_task_starts_exactly_once_across_reoffers() -> None:
    session = PlaceholderCallSession("sess-egress-once", _noop_signal, ice_servers=())
    try:
        await session.handle_offer(await _real_offer_sdp())
        first_task = session._egress_task
        assert first_task is not None and not first_task.done()

        await session.handle_offer(await _real_offer_sdp())  # ICE-restart re-offer
        assert session._egress_task is first_task
    finally:
        await session.close()


async def test_close_before_any_offer_does_not_hang_or_raise() -> None:
    """The connection can close before the client ever sends an offer —
    _egress_task is still None then, and close() must handle that."""
    session = PlaceholderCallSession("sess-close-early", _noop_signal, ice_servers=())
    await asyncio.wait_for(session.close(), timeout=2)
