"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-25 00:00:00.000000

Creates the pgvector extension (needed from day one per docs/12 §10's
Postgres-image decision, even though Phase 2 has no vector columns yet)
plus the 8 Phase-2 tables from docs/12 §3-4, hand-written to match the
DDL exactly rather than autogenerated (docs/12 §10: "autogenerate is a
draft, never a commit").

Table creation order respects FK dependencies: merchants first, then
wallet_accounts/merchant_limits/transactions (all FK merchants, and
transactions also FKs wallet_accounts), then the agent-zone tables
rooted at conversations.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "merchants",
        sa.Column("merchant_id", sa.Text(), primary_key=True),
        sa.Column("business_name", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("account_type", sa.Text(), nullable=False),
        sa.Column("preferred_language", sa.Text(), nullable=False, server_default="English"),
        sa.Column("merchant_since", sa.Date(), nullable=False),
        sa.Column("kyc_status", sa.Text(), nullable=False, server_default="verified"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "account_type IN ('Merchant Basic', 'Merchant Pro')",
            name="ck_merchants_account_type",
        ),
        sa.CheckConstraint(
            "kyc_status IN ('pending', 'verified', 'on_hold')",
            name="ck_merchants_kyc_status",
        ),
    )

    op.create_table(
        "wallet_accounts",
        sa.Column("wallet_id", sa.Text(), primary_key=True),
        sa.Column(
            "merchant_id",
            sa.Text(),
            sa.ForeignKey("merchants.merchant_id"),
            nullable=False,
            unique=True,
        ),
        sa.Column("balance_paise", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("currency", sa.CHAR(3), nullable=False, server_default="INR"),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint("balance_paise >= 0", name="ck_wallet_accounts_balance_paise"),
        sa.CheckConstraint("currency = 'INR'", name="ck_wallet_accounts_currency"),
    )

    op.create_table(
        "merchant_limits",
        sa.Column(
            "merchant_id", sa.Text(), sa.ForeignKey("merchants.merchant_id"), primary_key=True
        ),
        sa.Column("limit_type", sa.Text(), primary_key=True),
        sa.Column("limit_paise", sa.BigInteger(), nullable=False),
        sa.Column("used_paise", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("window_date", sa.Date(), nullable=False),
        sa.Column("request_id", sa.Text(), unique=True),
        sa.Column("requested_paise", sa.BigInteger()),
        sa.Column("request_status", sa.Text()),
        sa.Column("requested_at", sa.DateTime(timezone=True)),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "limit_type IN ('daily_txn', 'per_txn')", name="ck_merchant_limits_limit_type"
        ),
        sa.CheckConstraint("limit_paise > 0", name="ck_merchant_limits_limit_paise"),
        sa.CheckConstraint("used_paise >= 0", name="ck_merchant_limits_used_paise"),
        sa.CheckConstraint(
            "requested_paise > limit_paise", name="ck_merchant_limits_requested_paise"
        ),
        sa.CheckConstraint(
            "request_status IN ('submitted', 'approved', 'rejected')",
            name="ck_merchant_limits_request_status",
        ),
        sa.CheckConstraint(
            # 4-way pairing (not just request_id/request_status): Postgres
            # CHECKs pass vacuously on NULL, so a 2-way pairing alone would
            # let requested_paise/requested_at stay NULL on a "submitted"
            # request row.
            "(request_id IS NULL) = (request_status IS NULL)"
            " AND (request_status IS NULL) = (requested_paise IS NULL)"
            " AND (requested_paise IS NULL) = (requested_at IS NULL)",
            name="ck_merchant_limits_request_pair",
        ),
    )

    op.create_table(
        "transactions",
        sa.Column("txn_id", sa.Text(), primary_key=True),
        sa.Column(
            "merchant_id", sa.Text(), sa.ForeignKey("merchants.merchant_id"), nullable=False
        ),
        sa.Column(
            "wallet_id", sa.Text(), sa.ForeignKey("wallet_accounts.wallet_id"), nullable=False
        ),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("counterparty", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("decline_code", sa.Text()),
        sa.Column("http_status", sa.SmallInteger()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "type IN ('vendor_payment', 'qr_collection', 'settlement_credit', 'refund')",
            name="ck_transactions_type",
        ),
        sa.CheckConstraint("amount_paise > 0", name="ck_transactions_amount_paise"),
        sa.CheckConstraint(
            "status IN ('succeeded', 'declined', 'pending', 'refunded')",
            name="ck_transactions_status",
        ),
        sa.CheckConstraint(
            "(status = 'declined') = (decline_code IS NOT NULL)",
            name="ck_transactions_decline_code_pair",
        ),
    )
    op.create_index(
        "idx_txn_merchant_time",
        "transactions",
        ["merchant_id", sa.text("created_at DESC")],
    )

    op.create_table(
        "conversations",
        sa.Column("session_id", sa.Text(), primary_key=True),
        sa.Column("user_id", sa.Text(), sa.ForeignKey("merchants.merchant_id"), nullable=False),
        sa.Column("state", sa.Text(), nullable=False, server_default="created"),
        sa.Column("signaling_token_hash", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True)),
        sa.CheckConstraint(
            "state IN ('created', 'in_call', 'wrap_up', 'ended')", name="ck_conversations_state"
        ),
    )

    op.create_table(
        "conversation_turns",
        sa.Column(
            "session_id", sa.Text(), sa.ForeignKey("conversations.session_id"), primary_key=True
        ),
        sa.Column("turn_no", sa.Integer(), primary_key=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Integer()),
        sa.Column("input_tokens", sa.Integer()),
        sa.Column("output_tokens", sa.Integer()),
        sa.Column(
            "tool_calls",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
        sa.Column("cost_usd", sa.Numeric(10, 6)),
        sa.Column("trace_id", sa.Text()),
        sa.Column("text", sa.Text()),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("turn_no > 0", name="ck_conversation_turns_turn_no"),
        sa.CheckConstraint("role IN ('user', 'agent')", name="ck_conversation_turns_role"),
    )

    op.create_table(
        "tool_invocations",
        sa.Column(
            "invocation_id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "session_id", sa.Text(), sa.ForeignKey("conversations.session_id"), nullable=False
        ),
        sa.Column("turn_no", sa.Integer()),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column("input", postgresql.JSONB(), nullable=False),
        sa.Column("output", postgresql.JSONB()),
        sa.Column("screen_ctx", postgresql.JSONB()),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error_code", sa.Text()),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), unique=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "status IN ('ok', 'error', 'denied', 'pending_confirm', 'cancelled')",
            name="ck_tool_invocations_status",
        ),
        sa.CheckConstraint(
            "(status = 'error') = (error_code IS NOT NULL)",
            name="ck_tool_invocations_error_code_pair",
        ),
    )
    op.create_index("idx_tool_session", "tool_invocations", ["session_id", "created_at"])

    op.create_table(
        "call_costs",
        sa.Column(
            "session_id", sa.Text(), sa.ForeignKey("conversations.session_id"), primary_key=True
        ),
        sa.Column("stt_usd", sa.Numeric(10, 6), nullable=False),
        sa.Column("llm_dialogue_usd", sa.Numeric(10, 6), nullable=False),
        sa.Column("llm_utility_usd", sa.Numeric(10, 6), nullable=False),
        sa.Column("embeddings_usd", sa.Numeric(10, 6), nullable=False),
        sa.Column("tts_usd", sa.Numeric(10, 6), nullable=False),
        sa.Column("turn_infra_usd", sa.Numeric(10, 6), nullable=False, server_default="0"),
        sa.Column("total_usd", sa.Numeric(10, 6), nullable=False),
        sa.Column("stt_seconds", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("tts_chars", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "total_usd = stt_usd + llm_dialogue_usd + llm_utility_usd + embeddings_usd"
            " + tts_usd + turn_infra_usd",
            name="ck_call_costs_total_usd",
        ),
    )


def downgrade() -> None:
    # Deliberately does NOT `DROP EXTENSION vector` — it's a shared,
    # database-wide extension; tearing it down here would be a surprise to
    # anything else in the database that might already depend on it, for
    # a downgrade path this migration doesn't otherwise need to take.
    op.drop_table("call_costs")
    op.drop_index("idx_tool_session", table_name="tool_invocations")
    op.drop_table("tool_invocations")
    op.drop_table("conversation_turns")
    op.drop_table("conversations")
    op.drop_index("idx_txn_merchant_time", table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("merchant_limits")
    op.drop_table("wallet_accounts")
    op.drop_table("merchants")
