"""memory subsystem

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-05 00:00:00.000000

The Phase-5 memory tables: `conversation_summaries` (docs/12 §4.3),
`user_profiles` (docs/09 §5.1), and the vector zone's `kb_articles` +
`memory_chunks` (docs/12 §5, docs/09 §6.1). Hand-written to match the DDL
rather than autogenerated (docs/12 §10: "autogenerate is a draft, never a
commit" — it reliably misses CHECK constraints and the HNSW index, both
of which this revision depends on).

**The pgvector extension is NOT created here.** Revision 0001 already runs
`CREATE EXTENSION IF NOT EXISTS vector` — deliberately, from day one, even
though Phase 2 had no vector columns — and the Postgres image is
`pgvector/pgvector:pg16`, chosen in Phase 2 precisely so Phase 5 needs no
base-image migration (docs/12 §10, docs/16 ADR-003). `downgrade()` here
likewise does not drop it, for 0001's stated reason: it is a shared,
database-wide object and tearing it down would surprise anything else that
depends on it.

Table creation order respects FK dependencies: `conversation_summaries`
FKs `conversations` (created in 0001). `user_profiles`, `kb_articles`, and
`memory_chunks` have no FKs at all — see the model docstrings in
app/models/orm.py for why in each case (docs/09 declares no FK on
`user_profiles.user_id`; `memory_chunks.source_id` is polymorphic across
two tables and cannot reference either).

Two constraints here have no counterpart in either doc's DDL, both on
`memory_chunks.user_id`, both because docs/09 §6.2 makes the scoping
predicate a security invariant that only holds if the column is
well-formed:

- `ck_memory_chunks_user_scope` — both docs annotate the column "NULL for
  KB; REQUIRED for call_summary (scoping)" but neither declares a
  constraint, leaving the annotation unenforced. This revision declares
  the biconditional the annotation describes.
- `ck_memory_chunks_user_id_not_blank` — a blank `user_id` is not NULL, so
  it satisfies the biconditional above while matching no principal.

Rationale in full on `app.models.orm.MemoryChunk`.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# NOTE: `app.domain.types.EMBEDDING_DIM` is deliberately NOT imported here,
# even though it holds this same 1536 and app/models/orm.py rightly does
# import it. A migration is a frozen snapshot of one moment in schema
# history; a live constant makes a historical revision's DDL mutable. If a
# future model swap changed EMBEDDING_DIM to 3072, this revision would
# start creating vector(3072) — so every database that already ran 0002
# would hold vector(1536) while every freshly built one (CI's docker-gated
# job, a new dev machine, rebuilt staging) got vector(3072) from the same
# revision id, and the 0003 re-embed migration would have to ALTER a column
# whose current type differs by environment. The literal below is the
# schema as of 0002 and must never track the constant.

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "conversation_summaries",
        sa.Column(
            "session_id", sa.Text(), sa.ForeignKey("conversations.session_id"), primary_key=True
        ),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=False),
        sa.Column("intents", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("tools_used", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("turn_count", sa.Integer(), nullable=False),
        sa.Column("duration_s", sa.Integer(), nullable=False),
        # NUMERIC(8,4) is the rounded display copy; call_costs carries the
        # NUMERIC(10,6) ledger (docs/12 §4.5). Not a typo.
        sa.Column("cost_usd", sa.Numeric(8, 4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "resolution IN ('resolved', 'escalated', 'pending', 'abandoned')",
            name="ck_conversation_summaries_resolution",
        ),
    )
    op.create_index(
        "idx_summaries_user",
        "conversation_summaries",
        ["user_id", sa.text("created_at DESC")],
    )

    op.create_table(
        "user_profiles",
        # No FK to merchants: docs/09 §5.1 (the owning doc, canon §11)
        # declares a bare TEXT PRIMARY KEY.
        sa.Column("user_id", sa.Text(), primary_key=True),
        sa.Column("facts", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column(
            "preferences", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'")
        ),
        sa.Column(
            "open_issues", postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'")
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("updated_by_call", sa.Text()),
    )

    op.create_table(
        "kb_articles",
        sa.Column("slug", sa.Text(), primary_key=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "category IN ('limits', 'settlements', 'refunds', 'devices', 'kyc')",
            name="ck_kb_articles_category",
        ),
    )

    op.create_table(
        "memory_chunks",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text()),
        # Polymorphic (kb_articles.slug | conversations.session_id) —
        # deliberately no FK, a column cannot reference two tables.
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        # Literal, not EMBEDDING_DIM — see the import-block note above.
        sa.Column("embedding", Vector(1536), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "kind IN ('kb_article', 'call_summary')",
            name="ck_memory_chunks_kind",
        ),
        sa.CheckConstraint(
            # Beyond both docs' DDL: makes their "NULL for KB; REQUIRED for
            # call_summary (scoping)" annotation enforceable. See the module
            # docstring and app.models.orm.MemoryChunk.
            "(kind = 'call_summary') = (user_id IS NOT NULL)",
            name="ck_memory_chunks_user_scope",
        ),
        sa.CheckConstraint(
            # Separate from the biconditional deliberately. No folding
            # preserves it: an inner-AND variant permits a kb_article
            # carrying '', a btrim-replacement variant additionally permits
            # a call_summary with NULL user_id, and an OR'd variant permits
            # all three bad shapes. An AND-appended variant behaves the same
            # as this pair but collapses two invariants into one opaque
            # violation. A blank user_id is not NULL, so it satisfies the
            # biconditional while matching no principal. `~ '\\S'` rather
            # than one-argument `btrim`, which strips spaces only.
            r"user_id IS NULL OR user_id ~ '\S'",
            name="ck_memory_chunks_user_id_not_blank",
        ),
    )
    op.create_index(
        "idx_chunks_embedding",
        "memory_chunks",
        ["embedding"],
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )


def downgrade() -> None:
    # Deliberately does NOT `DROP EXTENSION vector` — 0001 created it and
    # documents why dropping a shared, database-wide extension on a
    # downgrade is the wrong move. Dropping it here would additionally
    # break 0001's own post-downgrade state, which assumes it present.
    op.drop_index("idx_chunks_embedding", table_name="memory_chunks")
    op.drop_table("memory_chunks")
    op.drop_table("kb_articles")
    op.drop_table("user_profiles")
    op.drop_index("idx_summaries_user", table_name="conversation_summaries")
    op.drop_table("conversation_summaries")
